apiVersion: v1
kind: ConfigMap
metadata:
  name: video-streaming-config
  namespace: video-streaming
data:
  application.yml: |
    server:
      port: 8080

    spring:
      data:
        mongodb:
          uri: mongodb://mongodb:27017/videodb
      kafka:
        bootstrap-servers: kafka:9092
        producer:
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        consumer:
          group-id: video-transcoding-group
          auto-offset-reset: earliest
          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
          properties:
            spring.json.trusted.packages: "com.video.transcoding.dto"
      servlet:
        multipart:
          max-file-size: 2GB
          max-request-size: 2GB

    minio:
      endpoint: http://minio:9000
      accessKey: minioadmin
      secretKey: minioadmin
      bucket: videos
      region: us-east-1

    video:
      processing:
        qualities:
          - name: "1080p"
            height: 1080
            bitrate: "4000k"
          - name: "720p"
            height: 720
            bitrate: "2500k"
          - name: "480p"
            height: 480
            bitrate: "1000k"
        temp-dir: /tmp/video-processing
        ffmpeg-path: /usr/bin/ffmpeg

    kafka:
      topics:
        transcoding: video-transcoding
        transcoding-result: video-transcoding-result

    sites:
      UNIT_1:
        name: "UNIT_1"
        ip: "192.168.205.108"
        endpoint: "http://192.168.205.108:8080/api/videos/share/sync"
      UNIT_2:
        name: "UNIT_2"
        ip: "192.168.205.104"
        endpoint: "http://192.168.205.104:8081/api/videos/share/sync" 