apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-data-pv
  namespace: video-streaming
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/zookeeper/data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-log-pv
  namespace: video-streaming
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/zookeeper/log
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-data-pv
  namespace: video-streaming
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/kafka/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-data-pvc
  namespace: video-streaming
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-log-pvc
  namespace: video-streaming
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-data-pvc
  namespace: video-streaming
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi 