apiVersion: v1
kind: Secret
metadata:
  name: video-streaming-secrets
  namespace: video-streaming
type: Opaque
data:
  # Các giá trị phải được encode base64
  minio-access-key: bWluaW9hZG1pbg==  # minioadmin
  minio-secret-key: bWluaW9hZG1pbg==  # minioadmin
  mongodb-username: YWRtaW4=  # admin
  mongodb-password: YWRtaW5wYXNzd29yZA==  # adminpassword 